version: '3'
services:
  database:
    build:
      context: ./database
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: songs-share
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    container_name: go-server-sample-db
    tty: true
    ports:
      - "3306:3306"
  server:
    build:
      context: ./server
    volumes:
      - "./server/src/:/go/src/github.com/estebanborai/go-server-sample/server/src/"
    container_name: go-server-sample-server
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - database
